name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - 'main'
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{steps.deployment.outputs.Production_URL}}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Install Vercel CLI
        run: pnpm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deployment
        run: |
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt
          vercel alias --token=${{ secrets.VERCEL_TOKEN }} set `cat deployment-url.txt` ${{secrets.DEPLOYMENT_URL}}
          echo "Production_URL=${{secrets.DEPLOYMENT_URL}}" >> "$GITHUB_OUTPUT"
      - name: Update website URL
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          curl -X PATCH \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO \
            -d '{"homepage": "${{secrets.DEPLOYMENT_URL}} "}'
