name: Vercel Production Deployment
permissions: write-all
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - 'develop'

jobs:
  Deploy-Staging:
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: ${{steps.deployment.outputs.Staging_URL}}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - name: Install Vercel CLI
        run: pnpm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN}}
      - name: Generate prisma client
        run: pnpm dlx prisma generate
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deployment
        run: |
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt
          vercel alias --token=${{ secrets.VERCEL_TOKEN }} set `cat deployment-url.txt` ${{vars.Staging_URL}}
          echo "Staging_URL=https://${{vars.Staging_URL}}" >> "$GITHUB_OUTPUT"
