name: Validate Pull Request
on: pull_request

jobs:
  Build:
    name: Building the project
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Installing dependencies...
        run: pnpm install
      - name: Building...
        run: pnpm build
